[INFO] [launch]: All log files can be found below /home/c/.ros/log/2024-10-13-22-58-33-471361-DESKTOP-DOID47Q-178638
[INFO] [launch]: Default logging verbosity is set to INFO
/home/c/weston_ws/MPC_planner/install/local_planner/share/local_planner/config.yaml
[INFO] [local_planner_node-1]: process started with pid [178640]
[INFO] [controller_node-2]: process started with pid [178642]
[controller_node-2] Exception ignored in: <function TransformListener.__del__ at 0x7f1989e41990>
[controller_node-2] Traceback (most recent call last):
[controller_node-2]   File "/opt/ros/humble/lib/python3.10/site-packages/tf2_ros/transform_listener.py", line 106, in __del__
[controller_node-2]     self.unregister()
[controller_node-2]   File "/opt/ros/humble/lib/python3.10/site-packages/tf2_ros/transform_listener.py", line 112, in unregister
[controller_node-2]     self.node.destroy_subscription(self.tf_sub)
[controller_node-2] AttributeError: 'TransformListener' object has no attribute 'node'
[local_planner_node-1] Traceback (most recent call last):
[local_planner_node-1]   File "/home/c/weston_ws/MPC_planner/install/local_planner/lib/local_planner/local_planner_node", line 33, in <module>
[local_planner_node-1]     sys.exit(load_entry_point('local-planner==0.0.0', 'console_scripts', 'local_planner_node')())
[local_planner_node-1]   File "/home/c/weston_ws/MPC_planner/install/local_planner/lib/python3.10/site-packages/local_planner/local_planner.py", line 359, in main
[local_planner_node-1]     phri_planner = LocalPlanner()
[local_planner_node-1]   File "/home/c/weston_ws/MPC_planner/install/local_planner/lib/python3.10/site-packages/local_planner/local_planner.py", line 19, in __init__
[local_planner_node-1]     self.replan_period = self.get_parameter('replan_period').get_parameter_value().double_value
[local_planner_node-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/node.py", line 602, in get_parameter
[local_planner_node-1]     raise ParameterNotDeclaredException(name)
[local_planner_node-1] rclpy.exceptions.ParameterNotDeclaredException: ('Invalid access to undeclared parameter(s)', 'replan_period')
[controller_node-2] Traceback (most recent call last):
[controller_node-2]   File "/home/c/weston_ws/MPC_planner/install/local_planner/lib/local_planner/controller_node", line 33, in <module>
[controller_node-2]     sys.exit(load_entry_point('local-planner==0.0.0', 'console_scripts', 'controller_node')())
[controller_node-2]   File "/home/c/weston_ws/MPC_planner/install/local_planner/lib/python3.10/site-packages/local_planner/controller.py", line 72, in main
[controller_node-2]     controller = Controller()
[controller_node-2]   File "/home/c/weston_ws/MPC_planner/install/local_planner/lib/python3.10/site-packages/local_planner/controller.py", line 25, in __init__
[controller_node-2]     self.listener = tf2_ros.TransformListener(self.tf_buffer)
[controller_node-2] TypeError: TransformListener.__init__() missing 1 required positional argument: 'node'
[ERROR] [local_planner_node-1]: process has died [pid 178640, exit code 1, cmd '/home/c/weston_ws/MPC_planner/install/local_planner/lib/local_planner/local_planner_node --ros-args -r __node:=local_planner_node'].
[ERROR] [controller_node-2]: process has died [pid 178642, exit code 1, cmd '/home/c/weston_ws/MPC_planner/install/local_planner/lib/local_planner/controller_node --ros-args -r __node:=controller_node'].